// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// Kmatfunc
arma::mat Kmatfunc(arma::mat Markers);
RcppExport SEXP GenomicMating_Kmatfunc(SEXP MarkersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Markers(MarkersSEXP);
    rcpp_result_gen = Rcpp::wrap(Kmatfunc(Markers));
    return rcpp_result_gen;
END_RCPP
}
// mapfunct
arma::vec mapfunct(arma::vec x);
RcppExport SEXP GenomicMating_mapfunct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(mapfunct(x));
    return rcpp_result_gen;
END_RCPP
}
// calculatecrossvalue
double calculatecrossvalue(arma::vec parent1, arma::vec parent2, arma::vec markereffects, double impvar);
RcppExport SEXP GenomicMating_calculatecrossvalue(SEXP parent1SEXP, SEXP parent2SEXP, SEXP markereffectsSEXP, SEXP impvarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type parent1(parent1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type parent2(parent2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type markereffects(markereffectsSEXP);
    Rcpp::traits::input_parameter< double >::type impvar(impvarSEXP);
    rcpp_result_gen = Rcpp::wrap(calculatecrossvalue(parent1, parent2, markereffects, impvar));
    return rcpp_result_gen;
END_RCPP
}
// getstats
arma::vec getstats(arma::mat Markers, arma::mat K, arma::vec markereffects, arma::mat P, double impvar);
RcppExport SEXP GenomicMating_getstats(SEXP MarkersSEXP, SEXP KSEXP, SEXP markereffectsSEXP, SEXP PSEXP, SEXP impvarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Markers(MarkersSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type markereffects(markereffectsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type P(PSEXP);
    Rcpp::traits::input_parameter< double >::type impvar(impvarSEXP);
    rcpp_result_gen = Rcpp::wrap(getstats(Markers, K, markereffects, P, impvar));
    return rcpp_result_gen;
END_RCPP
}
