# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Kmatfunc <- function(Markers) {
    .Call('GenomicMating_Kmatfunc', PACKAGE = 'GenomicMating', Markers)
}

mapfunct <- function(x) {
    .Call('GenomicMating_mapfunct', PACKAGE = 'GenomicMating', x)
}

calculatecrossvalue <- function(parent1, parent2, markereffects, impvar) {
    .Call('GenomicMating_calculatecrossvalue', PACKAGE = 'GenomicMating', parent1, parent2, markereffects, impvar)
}

getstats <- function(Markers, K, markereffects, P, impvar) {
    .Call('GenomicMating_getstats', PACKAGE = 'GenomicMating', Markers, K, markereffects, P, impvar)
}

