# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Kmatfunc <- function(Markers) {
    .Call(`_GenomicMating_Kmatfunc`, Markers)
}

mapfunct <- function(x) {
    .Call(`_GenomicMating_mapfunct`, x)
}

calculatecrossvalue <- function(parent1, parent2, markereffects) {
    .Call(`_GenomicMating_calculatecrossvalue`, parent1, parent2, markereffects)
}

getstats <- function(Markers, K, markereffects, P) {
    .Call(`_GenomicMating_getstats`, Markers, K, markereffects, P)
}

